version: '2'
services:
  nginx:
    image: nginx
    command: sh -c "sed -ri 's/user[[:space:]]+nginx/user www-data www-data/g' /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    restart: always
    volumes:
      - ./data/certs/${DOMAIN}/fullchain.pem:/etc/nginx/fullchain.pem:ro
      - ./data/certs/${DOMAIN}/privkey.pem:/etc/nginx/privkey.pem:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/letsencrypt.conf:/etc/nginx/letsencrypt.conf:ro
      - ./data/logs/nginx:/var/log/nginx
      - ./data/pydio:/srv/www
      - ./data/php:/php
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  php:
    build: ./php
    volumes:
      - ./data/run/mysqld:/run/mysqld
      - ./data/pydio:/srv/www
      - ./data/php:/php
      - ./php/docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
    dns:
      - 8.8.8.8
      - 8.8.4.4
  
  booster:
    build: ./pydio-booster
    volumes:
      - ./data/pydio:/srv/www
    environment:
      - SCHEMA=https
      - PYDIO_HOSTNAME=${DOMAIN}
      - PYDIO_PORT=${HTTPS_PORT}
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    dns:
      - 8.8.8.8
      - 8.8.4.4

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: 'pydio'
      MYSQL_USER: 'pydio'
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/run/mysqld:/run/mysqld
    dns:
      - 8.8.8.8
      - 8.8.4.4

  letsencrypt:
    build: letsencrypt
    environment: 
      - CF_EMAIL=${CF_EMAIL}
      - CF_KEY=${CF_KEY}
      - CF_DEBUG=true
      # Base directory for account key, generated certificates and list of domains (default: $SCRIPTDIR -- uses config directory if undefined)
      - BASEDIR="/dehydrated"
      # Minimum days before expiration to automatically renew certificate (default: 30)
      - RENEW_DAYS="30"
      # E-mail to use during the registration (default: <unset>)
      - CONTACT_EMAIL=${EMAIL}
      # Path to certificate authority (default: https://acme-v01.api.letsencrypt.org/directory)
      #- CA="https://acme-v01.api.letsencrypt.org/directory"
      #- CA="https://acme-staging.api.letsencrypt.org/directory"
      # Use eva and matt CloudFlare DNS servers
      # - CF_DNS_SERVERS='173.245.58.114 173.245.59.131'
    volumes: 
      - ./data/certs:/dehydrated/certs
      - ./data/letsencrypt/accounts:/dehydrated/accounts
      - ./letsencrypt/domains.txt:/dehydrated/domains.txt:ro